export const SET_CURRENT_LEVEL = "SET_CURRENT_LEVEL";
export const UPDATE_STATE = "UPDATE_STATE";
export const CLEAR_STATE = "CLEAR_STATE";
export const CLEAR_LOADING_STATE = "CLEAR_LOADING_STATE";
export const SET_SCORE_STATS = "SET_SCORE_STATS";

// Additional Form
export const UPDATE_ADDITIONAL_FORM_STATE = "UPDATE_ADDITIONAL_FORM_STATE";
export const CLEAR_FORM_STATE = "CLEAR_FORM_STATE";
export const SET_SUBSCRIPTION_FORM_CURRENT_LEVEL = "SET_SUBSCRIPTION_FORM_CURRENT_LEVEL";
export const CLEAR_LOADING_ADDITIONAL_FORM_STATE = "CLEAR_LOADING_ADDITIONAL_FORM_STATE";
export const UPDATE_ADDITIONAL_FIELD_STATE = "UPDATE_ADDITIONAL_FIELD_STATE";
export const UPDATE_PAYMENT_FORM_STATE = "UPDATE_PAYMENT_FORM_STATE";
export const TOGGLE_SUBSCRIPTION_COMPLETION_STATE = "TOGGLE_SUBSCRIPTION_COMPLETION_STATE";
export const UPDATE_SELECTED_OFFER_STATE = "UPDATE_SELECTED_OFFER_STATE";
export const TOGGLE_SUBSCRIPTION_OFFER_REQ_STATE = "TOGGLE_SUBSCRIPTION_OFFER_REQ_STATE";
export const FORM_INFO_SUCCESSFULL = "FORM_INFO_SUCCESSFULL";
export const FORMS_HANDLE_FIELD_CHANGE = "FORMS_HANDLE_FIELD_CHANGE";